// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return windows;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdcJz9YF9bLE8bcx4C9M5-20wlwEqcP6Y',
    appId: '1:535582329844:android:880b35f9de5c65a1a007a1',
    messagingSenderId: '535582329844',
    projectId: 'taskmate-86227',
    storageBucket: 'taskmate-86227.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpMwvYUfhl8Ejzl2o3XCj91j2rtAVVxcI',
    appId: '1:535582329844:ios:172452cda9c645bca007a1',
    messagingSenderId: '535582329844',
    projectId: 'taskmate-86227',
    storageBucket: 'taskmate-86227.firebasestorage.app',
    iosBundleId: 'com.taskmate.taskmate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpMwvYUfhl8Ejzl2o3XCj91j2rtAVVxcI',
    appId: '1:535582329844:ios:172452cda9c645bca007a1',
    messagingSenderId: '535582329844',
    projectId: 'taskmate-86227',
    storageBucket: 'taskmate-86227.firebasestorage.app',
    iosBundleId: 'com.taskmate.taskmate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-JcMiBN04vY-fpQjZ0YPfCxeNwtasIuc',
    appId: '1:535582329844:web:0d369085343a6b10a007a1',
    messagingSenderId: '535582329844',
    projectId: 'taskmate-86227',
    authDomain: 'taskmate-86227.firebaseapp.com',
    storageBucket: 'taskmate-86227.firebasestorage.app',
    measurementId: 'G-H417XCY9GJ',
  );
}
